DROP DATABASE IF EXISTS oficina_lp4x4;
CREATE DATABASE oficina_lp4x4 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE oficina_lp4x4;

CREATE TABLE CLIENTE (
  ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Telefone VARCHAR(15),
  Email VARCHAR(100)
);

CREATE TABLE VEICULO (
  ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
  Placa VARCHAR(10) NOT NULL UNIQUE,
  Modelo VARCHAR(50),
  Quilometragem INT,
  ID_CLIENTE INT,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE MECANICO (
  ID_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Especialidade VARCHAR(50)
);

CREATE TABLE ORDEM_SERVICO (
  ID_OS INT AUTO_INCREMENT PRIMARY KEY,
  Data_Entrada DATE NOT NULL,
  Data_Saida DATE,
  Status VARCHAR(20) DEFAULT 'Em andamento',
  Valor_Total DECIMAL(10,2) DEFAULT 0.00,
  ID_CLIENTE INT,
  ID_VEICULO INT,
  ID_MECANICO INT,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
  FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO) ON DELETE CASCADE,
  FOREIGN KEY (ID_MECANICO) REFERENCES MECANICO(ID_MECANICO)
);

CREATE TABLE SERVICO (
  ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
  Descricao VARCHAR(200) NOT NULL,
  Valor DECIMAL(10,2) NOT NULL,
  ID_OS INT,
  FOREIGN KEY (ID_OS) REFERENCES ORDEM_SERVICO(ID_OS) ON DELETE CASCADE
);

CREATE TABLE PECA_ESTOQUE (
  ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
  Nome_Peca VARCHAR(100) NOT NULL,
  Quantidade INT DEFAULT 0,
  Preco_Unitario DECIMAL(10,2) NOT NULL
);

CREATE TABLE ITENS_OS (
  ID_OS INT,
  ID_PECA INT,
  Quantidade_Usada INT NOT NULL DEFAULT 1,
  Valor_Unitario DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_OS, ID_PECA),
  FOREIGN KEY (ID_OS) REFERENCES ORDEM_SERVICO(ID_OS) ON DELETE CASCADE,
  FOREIGN KEY (ID_PECA) REFERENCES PECA_ESTOQUE(ID_PECA)
);

-- Trigger: atualiza Valor_Total ao inserir serviço
DELIMITER $$
CREATE TRIGGER trig_atualiza_valor_servico AFTER INSERT ON SERVICO
FOR EACH ROW
BEGIN
    UPDATE ORDEM_SERVICO os
    SET Valor_Total = (
        SELECT COALESCE(SUM(s.Valor), 0) FROM SERVICO s WHERE s.ID_OS = NEW.ID_OS
    ) + (
        SELECT COALESCE(SUM(io.Quantidade_Usada * io.Valor_Unitario), 0) 
        FROM ITENS_OS io WHERE io.ID_OS = NEW.ID_OS
    )
    WHERE os.ID_OS = NEW.ID_OS;
END$$
DELIMITER ;

-- Trigger: atualiza Valor_Total ao inserir peça
DELIMITER $$
CREATE TRIGGER trig_atualiza_valor_peca AFTER INSERT ON ITENS_OS
FOR EACH ROW
BEGIN
    UPDATE ORDEM_SERVICO os
    SET Valor_Total = (
        SELECT COALESCE(SUM(s.Valor), 0) FROM SERVICO s WHERE s.ID_OS = NEW.ID_OS
    ) + (
        SELECT COALESCE(SUM(io.Quantidade_Usada * io.Valor_Unitario), 0) 
        FROM ITENS_OS io WHERE io.ID_OS = NEW.ID_OS
    )
    WHERE os.ID_OS = NEW.ID_OS;
END$$
DELIMITER ;
